#!/bin/bash

if [ "$(stat -c "%Y" "${APPLICATION_INST}/bin/set-bitbucket-home.sh")" -eq "0" ]; then
  sed --in-place "s~^.*BITBUCKET_HOME=$~  BITBUCKET_HOME=$APPLICATION_HOME~" ${APPLICATION_INST}/bin/set-bitbucket-home.sh
fi

if [ "$(stat -c "%Y" "${APPLICATION_INST}/bin/_start-webapp.sh")" -eq "0" ];
  then
    if [ -n "${JVM_MEMORY_MIN}" ];
      then
        sed --in-place "s~JVM_MINIMUM_MEMORY=.*~JVM_MINIMUM_MEMORY=${JVM_MEMORY_MIN}~" ${APPLICATION_INST}/bin/_start-webapp.sh
    fi
    if [ -n "${JVM_MEMORY_MAX}" ];
      then
        sed --in-place "s~JVM_MAXIMUM_MEMORY=.*~JVM_MAXIMUM_MEMORY=${JVM_MEMORY_MAX}~" ${APPLICATION_INST}/bin/_start-webapp.sh
    fi
    if [ -n "${JVM_ARGUMENTS}" ];
      then
        sed --in-place "s~#JVM_SUPPORT_RECOMMENDED_ARGS=~JVM_SUPPORT_RECOMMENDED_ARGS=\"${JVM_ARGUMENTS}\"~" ${APPLICATION_INST}/bin/_start-webapp.sh
    fi
fi

exec "$@"